#!/usr/bin/env python3
"""
Renders templates/index.html into a deterministic local ``public/`` preview.

Fix over the previous version: the build crashed. index.html contains
``{{ user_name|tojson }}`` and ``{{ user_name_set|tojson }}``, and neither
variable was passed, so Jinja handed ``Undefined`` to json.dumps and raised
``TypeError: Object of type Undefined is not JSON serializable``. Static builds
therefore failed. All template variables are now supplied
explicitly, with ``debug`` omitted so the public build leaks no local paths.
Template assets are relative so a repository subpath works, and an
optional API base is emitted as a JSON string literal rather than executable
string interpolation.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

from flask import Flask, render_template

from modules import compat, safety

PUBLIC_DIR = compat.project_path("public")

# Never copy the directory wholesale: ``static/`` also receives ignored runtime
# files (for example current.png) and may contain private local leftovers. A
# release artifact must be identical in every checkout.
STATIC_FILES = (
    "blinking.png",
    "cheeky.png",
    "config.js",
    "dissapointed.png",
    "idle.png",
    "sad.png",
    "smile.png",
    "talking.png",
    "thinking.png",
)

app = Flask(
    __name__,
    template_folder=str(compat.project_path("templates")),
    static_folder=str(compat.project_path("static")),
)


def build(api_base: str | None = None) -> Path:
    if PUBLIC_DIR.exists():
        shutil.rmtree(PUBLIC_DIR)
    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)

    with app.app_context():
        html = render_template(
            "index.html",
            persona=None,          # never publish the persona
            memory=[],
            user_name="",          # required: the template runs it through |tojson
            user_name_set=False,
            safety_consent_version=str(safety.DISCLOSURE_VERSION),
            # 'debug' is intentionally left undefined; the template guards it
            # with {% if debug is defined %} so local paths stay private.
        )

    index = PUBLIC_DIR / "index.html"
    index.write_text(html, encoding="utf-8")

    static_dest = PUBLIC_DIR / "static"
    static_dest.mkdir()
    for filename in STATIC_FILES:
        source = compat.project_path("static", filename)
        if not source.is_file():
            raise FileNotFoundError(f"Required static asset is missing: {filename}")
        shutil.copy2(source, static_dest / filename)

    # Point the static page at a public API endpoint, if one was provided.
    api_base = (api_base if api_base is not None
                else os.getenv("API_BASE_URL", "")).rstrip("/")
    if api_base:
        # config.js is JavaScript, but a JSON string literal is also a valid
        # JavaScript string literal.  Encoding it prevents quotes, newlines or
        # backslashes in an environment variable from becoming executable JS.
        encoded_api_base = json.dumps(api_base, ensure_ascii=True)
        (static_dest / "config.js").write_text(
            "// Auto-generated by build_static_site.py\n"
            f"window.API_BASE_URL = {encoded_api_base};\n",
            encoding="utf-8",
        )

    return index


if __name__ == "__main__":
    output = build()
    print(f"Built {output}")
    sys.exit(0)
